### PR TITLE
added Right and Left classes

### PR DESCRIPTION
**Pull request by johannesgerer**

### CODE REVIEW

**Comment by 3noch** [comment]
Won't these be easily confused with the constructors of `Either`?

**Comment by johannesgerer** [comment]
No, as the Either constructors are uppercase and the new functions are lower case.

**Comment by 3noch** [comment]
True, but the class names are identical to Either's constructors. Granted, it's type vs value level, but still...

**Comment by johannesgerer** [comment]
I would not mind it and I think it is consistent. There are many actual clashes with prelude and even they are justified I think. But you decide.

**Comment by seanparsons** [comment]
Well the build errors need to be fixed first, but I think I need to have a little bit of a think about this one.

**Comment by turion** [comment]
> There are many actual clashes with prelude

Yep, that's bound to happen in a DSL library. I'll merge this if you can rebase on `master` and fix the build errors.

**Pull request closed without merging**
