### PR TITLE
Fix Haddock build

### PR DESCRIPTION
**Pull request by ddssff**

### CODE REVIEW

**Review by turion — COMMENTED** [review]
But removing the `|` will remove the haddock string completely. I think that's not what we want, right?

**Comment by ddssff** [comment]
I don't think that is a valid place for a haddock string, but I should check the haddock output.

**Comment by ddssff** [comment]
This additional patch restores the haddock output.

**Comment by ddssff** [comment]
Would you prefer this as a single patch?

**Comment by turion** [comment]
> Would you prefer this as a single patch?

Not necessary, I've squashed already. Thanks!

**Pull request merged**
